# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme             : "mmistakes/minimal-mistakes@4.13.0"
# minimal_mistakes_skin    : dark # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-CA"
title                    : ""
title_separator          : ""
name                     : ""
description              : ""
url                      : https://jranaraki.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : jranaraki/jranaraki.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : false # true, false (default)

# Social Sharing
twitter:
  username               : jranaraki
github:
  username               : jranaraki
og_image                 : # Open Graph/Twitter default site image

# Site Author
Ryen Tang:
  name             : "Javad Rahimipour Anaraki"
  avatar           : "Me.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : 
  location         : "Toronto, Canada"
  email            :
  uri              : "https://jranaraki.github.io"
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "jranaraki"
  foursquare       :
  github           : "jranaraki"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "jranaraki"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "jranaraki"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"
